Repository AntelopeIO/spring, pull requests merged in 2024-09, with the labels that each got.

#681 [1.0] Test accept_block_header, accept_block, and irreversible_block signals
  libraries/testing/include/eosio/testing/tester.hpp
  libraries/testing/tester.cpp
Labels: OCI

#699 [1.0 -> main] Test accept_block_header, accept_block, and irreversible_block signals
  libraries/testing/include/eosio/testing/tester.hpp
  libraries/testing/tester.cpp
Labels: OCI

#698 [1.0] Harden ordered_diff
  libraries/chain/include/eosio/chain/finality/finalizer_policy.hpp
  libraries/chain/include/eosio/chain/finality/proposer_policy.hpp
  libraries/libfc/include/fc/container/ordered_diff.hpp
  libraries/libfc/test/test_ordered_diff.cpp
Labels: bug, OCI, validation-protocol

#703 [1.0 -> main] Harden ordered_diff; Version bump v1.0.0 final
  README.md
  libraries/chain/include/eosio/chain/finality/finalizer_policy.hpp
  libraries/chain/include/eosio/chain/finality/proposer_policy.hpp
  libraries/libfc/include/fc/container/ordered_diff.hpp
  libraries/libfc/test/test_ordered_diff.cpp
Labels: OCI

#671 [1.0.1] P2P: syncing fix
  plugins/net_plugin/net_plugin.cpp
Labels: OCI

#704 [1.0.1] P2P: Sync timeout
  plugins/net_plugin/net_plugin.cpp
Labels: OCI

#706 [1.0.1 -> main] P2P: Sync timeout
  plugins/net_plugin/net_plugin.cpp
Labels: OCI

#700 [1.0.1] Verify block signature first when creating block_state
  libraries/chain/block_state.cpp
  libraries/chain/include/eosio/chain/block_state.hpp
Labels: OCI

#716 [1.0.1 -> main] Verify block signature first when creating block_state
  libraries/chain/block_state.cpp
  libraries/chain/include/eosio/chain/block_state.hpp
Labels: OCI

#710 [1.0.1] Load header_exts of root in forkdb
  libraries/chain/fork_database.cpp
  libraries/chain/include/eosio/chain/block_header_state.hpp
  libraries/chain/include/eosio/chain/block_header_state_legacy.hpp
  unittests/finalizer_vote_tests.cpp
  unittests/savanna_disaster_recovery_tests.cpp
Labels: OCI

#708 [1.0.1] Test: Rewrite P2P sync throttle test
  tests/TestHarness/Node.py
  tests/gelf_test.py
  tests/p2p_sync_throttle_test.py
  tests/p2p_sync_throttle_test_shape.json
Labels: OCI

#717 [1.0.1 -> main] Load header_exts of root in forkdb
  libraries/chain/fork_database.cpp
  libraries/chain/include/eosio/chain/block_header_state.hpp
  libraries/chain/include/eosio/chain/block_header_state_legacy.hpp
  unittests/finalizer_vote_tests.cpp
  unittests/savanna_disaster_recovery_tests.cpp
Labels: OCI

#718 [1.0.1 -> main] Test: Rewrite P2P sync throttle test
  tests/TestHarness/Node.py
  tests/gelf_test.py
  tests/p2p_sync_throttle_test.py
  tests/p2p_sync_throttle_test_shape.json
Labels: OCI

#733 [1.0.1] Flush deep-mind logger after each message
  libraries/libfc/src/log/dmlog_appender.cpp
Labels: OCI

#739 [1.0.1 -> main] Flush deep-mind logger after each message
  libraries/libfc/src/log/dmlog_appender.cpp
Labels: enhancement, OCI

#740 [1.0.1 -> main] Small improvements left in PR 715
  libraries/chain/controller.cpp
Labels: bug

#738 [1.0.1] Should never move from a signed_block in a shared_ptr
  unittests/block_tests.cpp
  unittests/forked_tests.cpp
  unittests/protocol_feature_tests.cpp
Labels: OCI, test-instability

#755 [1.0.1 -> main] Should never move from a signed_block in a shared_ptr
  unittests/block_tests.cpp
  unittests/forked_tests.cpp
  unittests/protocol_feature_tests.cpp
Labels: OCI

#750 [1.0.1] Log received block with qc_claim even if no qc
  libraries/chain/controller.cpp
Labels: OCI

#744 [1.0.1] Make signed_block_ptr const
  libraries/chain/block_state.cpp
  libraries/chain/block_state_legacy.cpp
  libraries/chain/controller.cpp
  libraries/chain/include/eosio/chain/block.hpp
  libraries/chain/include/eosio/chain/block_state.hpp
  libraries/chain/include/eosio/chain/block_state_legacy.hpp
  libraries/libfc/include/fc/io/raw.hpp
  libraries/libfc/include/fc/io/raw_fwd.hpp
  plugins/chain_plugin/test/test_trx_finality_status_processing.cpp
  plugins/chain_plugin/test/test_trx_retry_db.cpp
  plugins/trace_api_plugin/test/include/eosio/trace_api/test_common.hpp
  tests/block_log.cpp
  tests/chain_plugin_tests.cpp
  unittests/block_log_extract.cpp
  unittests/producer_schedule_tests.cpp
  unittests/unapplied_transaction_queue_tests.cpp
  unittests/vote_processor_tests.cpp
Labels: OCI

#760 [1.0.1 -> main] Log received block with qc_claim even if no qc
  libraries/chain/controller.cpp
Labels: OCI

#761 [1.0.1 -> main] Make signed_block_ptr const
  libraries/chain/block_state.cpp
  libraries/chain/block_state_legacy.cpp
  libraries/chain/controller.cpp
  libraries/chain/include/eosio/chain/block.hpp
  libraries/chain/include/eosio/chain/block_state.hpp
  libraries/chain/include/eosio/chain/block_state_legacy.hpp
  libraries/libfc/include/fc/io/raw.hpp
  libraries/libfc/include/fc/io/raw_fwd.hpp
  plugins/chain_plugin/test/test_trx_finality_status_processing.cpp
  plugins/chain_plugin/test/test_trx_retry_db.cpp
  plugins/trace_api_plugin/test/include/eosio/trace_api/test_common.hpp
  tests/block_log.cpp
  tests/chain_plugin_tests.cpp
  unittests/block_log_extract.cpp
  unittests/producer_schedule_tests.cpp
  unittests/unapplied_transaction_queue_tests.cpp
  unittests/vote_processor_tests.cpp
Labels: OCI

#713 [1.0.1] Fix pause production on missed round
  plugins/producer_plugin/include/eosio/producer_plugin/production_pause_vote_tracker.hpp
  plugins/producer_plugin/producer_plugin.cpp
  plugins/producer_plugin/test/CMakeLists.txt
  plugins/producer_plugin/test/test_production_pause_vote_tracker.cpp
  tests/production_pause_vote_timeout.py
  tests/production_pause_vote_timeout_test_shape.json
  tests/ship_streamer_test.py
Labels: bug, OCI

#736 Move verify_qc onto the chain thread pool
  libraries/chain/controller.cpp
  libraries/chain/include/eosio/chain/thread_utils.hpp
Labels: enhancement, OCI

#772 [1.0.2] Enable debug logging of the vote logger for unittest --verbose
  unittests/main.cpp
Labels: OCI

#774 [1.0.2 -> main] Enable debug logging of the vote logger for unittest --verbose
  unittests/main.cpp
Labels: OCI

#768 [1.0.2] Remove explicit net_plugin pause during snapshot
  plugins/net_plugin/net_plugin.cpp
Labels: bug, OCI

#784 [1.0.2 -> main] Remove explicit net_plugin pause during snapshot
  plugins/net_plugin/net_plugin.cpp
Labels: OCI

#792 [1.0.2 -> main] Test: p2p_sync_throttle_test. Increase sync timeout.
  tests/p2p_sync_throttle_test.py
Labels: OCI

#799 [1.0.2] Update Produced block and Received block logs
  libraries/chain/controller.cpp
Labels: OCI

#800 [1.0.2 -> main] Update Produced block and Received block logs
  libraries/chain/controller.cpp
Labels: OCI

#777 [1.0.2] P2P: Allow irreversible mode syncing to continue when LIB is paused
  libraries/chain/controller.cpp
  libraries/chain/include/eosio/chain/controller.hpp
  plugins/net_plugin/net_plugin.cpp
  tests/nodeos_startup_catchup.py
Labels: OCI

#803 P2P: Remove dead code
  plugins/net_plugin/net_plugin.cpp
Labels: OCI

#785 P2P: Improve performance by not serializing and deserializing blocks from block log
  libraries/chain/block_log.cpp
  libraries/chain/controller.cpp
  libraries/chain/include/eosio/chain/block_log.hpp
  libraries/chain/include/eosio/chain/controller.hpp
  libraries/chain/include/eosio/chain/log_catalog.hpp
  plugins/net_plugin/net_plugin.cpp
Labels: enhancement

#811 [1.0.2] Prevent sync ahead in irreversible mode
  plugins/net_plugin/net_plugin.cpp
  tests/TestHarness/Node.py
  tests/nodeos_startup_catchup.py
Labels: OCI

#814 [1.0.2 -> main] Prevent sync ahead in irreversible mode
  plugins/net_plugin/net_plugin.cpp
  tests/TestHarness/Node.py
  tests/nodeos_startup_catchup.py
Labels: OCI

#816 [1.0.2] SHiP: Fix hang on shutdown
  plugins/state_history_plugin/include/eosio/state_history_plugin/session.hpp
  plugins/state_history_plugin/state_history_plugin.cpp
  tests/CMakeLists.txt
  tests/ship_kill_client_test.py
Labels: bug, OCI

#820 [1.0.2 -> main] SHiP: Fix hang on shutdown
  plugins/state_history_plugin/include/eosio/state_history_plugin/session.hpp
  plugins/state_history_plugin/state_history_plugin.cpp
  tests/CMakeLists.txt
  tests/ship_kill_client_test.py
Labels: OCI

#825 [5.0.3 -> 1.0.3] P2P: Resolve on reconnect
  plugins/net_plugin/net_plugin.cpp
Labels: OCI

#619 Optimize block processing - Part 1
  libraries/chain/controller.cpp
  libraries/chain/fork_database.cpp
  libraries/chain/include/eosio/chain/block_handle.hpp
  libraries/chain/include/eosio/chain/controller.hpp
  libraries/chain/include/eosio/chain/fork_database.hpp
  libraries/testing/include/eosio/testing/tester.hpp
  libraries/testing/tester.cpp
  plugins/chain_interface/include/eosio/chain/plugin_interface.hpp
  plugins/chain_plugin/chain_plugin.cpp
  plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
  plugins/net_plugin/net_plugin.cpp
  plugins/producer_plugin/include/eosio/producer_plugin/producer_plugin.hpp
  plugins/producer_plugin/producer_plugin.cpp
  plugins/prometheus_plugin/metrics.hpp
  tests/CMakeLists.txt
  tests/lib_advance_test.py
  tests/p2p_sync_throttle_test.py
  unittests/block_tests.cpp
  unittests/fork_db_tests.cpp
  unittests/forked_tests.cpp
  unittests/protocol_feature_tests.cpp
Labels: OCI

#688 Optimize block processing - Part 2
  libraries/chain/controller.cpp
  libraries/chain/include/eosio/chain/controller.hpp
  plugins/chain_interface/include/eosio/chain/plugin_interface.hpp
  plugins/chain_plugin/chain_plugin.cpp
  plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
  plugins/net_plugin/net_plugin.cpp
  plugins/producer_plugin/include/eosio/producer_plugin/producer_plugin.hpp
  plugins/producer_plugin/producer_plugin.cpp
  tests/nodeos_startup_catchup.py
Labels: OCI

#802 Optimize block processing - Part 3
  libraries/custom_appbase/CMakeLists.txt
  libraries/custom_appbase/include/eosio/chain/application.hpp
  libraries/custom_appbase/include/eosio/chain/exec_pri_queue.hpp
  libraries/custom_appbase/tests/CMakeLists.txt
  libraries/custom_appbase/tests/custom_appbase_tests.cpp
  plugins/net_plugin/net_plugin.cpp
  tests/nodeos_startup_catchup.py
Labels: OCI

#826 [1.0.2 -> main] P2P: Resolve on reconnect
  plugins/net_plugin/net_plugin.cpp
Labels: OCI

#838 [1.0.2] P2P: Normally wait for connection monitor to reconnect
  plugins/net_plugin/net_plugin.cpp
Labels: OCI

#844 [1.0.2 -> main] P2P: Normally wait for connection monitor to reconnect
  plugins/net_plugin/net_plugin.cpp
Labels: OCI
