Repository AntelopeIO/spring, pull requests merged in 2024-10, with the labels that each got.

#839 [1.0.2] P2P: Change handshake logs to debug instead of info
  plugins/net_plugin/net_plugin.cpp
Labels: OCI

#847 [1.0.2 -> main] P2P: Change handshake logs to debug instead of info
  plugins/net_plugin/net_plugin.cpp
Labels: OCI

#845 [1.0.2] SHiP: Fix hang on exit
  plugins/state_history_plugin/state_history_plugin.cpp
Labels: OCI

#852 [1.0.2 -> main] SHiP: Fix hang on exit
  plugins/state_history_plugin/state_history_plugin.cpp
Labels: OCI

#854 [1.0.2] Test fix: p2p_sync_throttle_test
  tests/CMakeLists.txt
  tests/p2p_sync_throttle_test.py
Labels: OCI, test-instability

#788 [1.0.2] Don't assume that claimed block is in fork_db.
  libraries/chain/controller.cpp
  libraries/chain/fork_database.cpp
  libraries/chain/include/eosio/chain/block_state.hpp
  libraries/chain/include/eosio/chain/block_state_legacy.hpp
  libraries/chain/include/eosio/chain/fork_database.hpp
  unittests/fork_db_tests.cpp
  unittests/forked_tests_savanna.cpp
  unittests/savanna_cluster.cpp
  unittests/savanna_cluster.hpp
  unittests/savanna_cluster_tests.cpp
  unittests/savanna_disaster_recovery_tests.cpp
  unittests/savanna_misc_tests.cpp
  unittests/savanna_proposer_policy_tests.cpp
  unittests/savanna_transition_tests.cpp
Labels: bug

#853 [1.0.2] P2P: Resolve on reconnect
  plugins/net_plugin/net_plugin.cpp
Labels: bug, OCI

#883 [1.0.3 -> main] Fix issue with block report log time including the time for maybe_switch_forks
  plugins/producer_plugin/producer_plugin.cpp
Labels: bug

#875 [1.0.3] Fix flaky nodeos_snapshot_diff_test due to a race condition
  tests/nodeos_snapshot_diff_test.py
Labels: test-bug

#885 [1.0.3 -> main] Fix flaky nodeos_snapshot_diff_test due to a race condition
  tests/nodeos_snapshot_diff_test.py
Labels: test-bug

#899 [1.0.3] P2P: Schedule a retry of enqueue_sync_block when throttled
  plugins/net_plugin/net_plugin.cpp
Labels: OCI

#900 [1.0.3 -> main] P2P: Schedule a retry of enqueue_sync_block when throttled
  plugins/net_plugin/net_plugin.cpp
Labels: OCI

#908 [1.0.3] Test failure: distributed-transactions-if-test
  tests/TestHarness/Node.py
Labels: bug, test-instability

#879 [1.0.3] P2P: Resolve on reconnect - Take 3
  plugins/net_plugin/net_plugin.cpp
Labels: bug, OCI

#911 [1.0.3 -> main] P2P: Resolve on reconnect - Take 3
  plugins/net_plugin/net_plugin.cpp
Labels: OCI

#909 Create socket with provided executor
  libraries/libfc/include/fc/network/listener.hpp
  plugins/http_plugin/http_plugin.cpp
  plugins/net_plugin/net_plugin.cpp
  plugins/state_history_plugin/include/eosio/state_history_plugin/session.hpp
  plugins/state_history_plugin/state_history_plugin.cpp
Labels: OCI

#912 P2P: Immediately close on bad block
  plugins/net_plugin/net_plugin.cpp
Labels: OCI

#913 [1.0.3] Optimize handling of invalid vote message
  plugins/net_plugin/net_plugin.cpp
Labels: OCI

#914 [1.0.3 -> main] Optimize handling of invalid vote message
  plugins/net_plugin/net_plugin.cpp
Labels: OCI

#904 [1.0.3] fix eosvmoc_limits_tests on non-x86 and non-Linux (where OC is not supported)
  unittests/eosvmoc_limits_tests.cpp
Labels: test-bug

#918 Normalize usage of LIB
  docs/01_nodeos/04_replays/how-to-replay-from-a-blocks.log.md
  libraries/chain/controller.cpp
  libraries/chain/fork_database.cpp
  libraries/chain/include/eosio/chain/config.hpp
  libraries/chain/include/eosio/chain/controller.hpp
  libraries/chain/include/eosio/chain/fork_database.hpp
  libraries/custom_appbase/include/eosio/chain/exec_pri_queue.hpp
  libraries/testing/include/eosio/testing/tester.hpp
  libraries/testing/tester.cpp
  plugins/chain_interface/include/eosio/chain/plugin_interface.hpp
  plugins/chain_plugin/account_query_db.cpp
  plugins/chain_plugin/chain_plugin.cpp
  plugins/net_plugin/include/eosio/net_plugin/protocol.hpp
  plugins/net_plugin/net_plugin.cpp
  plugins/producer_plugin/producer_plugin.cpp
  plugins/state_history_plugin/include/eosio/state_history_plugin/session.hpp
  programs/spring-util/actions/blocklog.cpp
  unittests/blocks_log_replay_tests.cpp
  unittests/finalizer_vote_tests.cpp
  unittests/fork_db_tests.cpp
  unittests/forked_tests.cpp
  unittests/savanna_cluster.hpp
  unittests/savanna_misc_tests.cpp
  unittests/state_history_tests.cpp
  unittests/vote_processor_tests.cpp
Labels: OCI

#922 Limit apply blocks
  libraries/chain/controller.cpp
  libraries/chain/include/eosio/chain/controller.hpp
  plugins/chain_interface/include/eosio/chain/plugin_interface.hpp
  plugins/net_plugin/net_plugin.cpp
  plugins/producer_plugin/include/eosio/producer_plugin/producer_plugin.hpp
  plugins/producer_plugin/producer_plugin.cpp
Labels: OCI

#920 Move get_info off main thread and run in http thread
  libraries/chain/include/eosio/chain/chain_id_type.hpp
  libraries/libfc/include/fc/crypto/hex.hpp
  plugins/chain_api_plugin/chain_api_plugin.cpp
  plugins/chain_plugin/CMakeLists.txt
  plugins/chain_plugin/chain_plugin.cpp
  plugins/chain_plugin/get_info_db.cpp
  plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
  plugins/chain_plugin/include/eosio/chain_plugin/get_info_db.hpp
  plugins/prometheus_plugin/metrics.hpp
  programs/cleos/main.cpp
  tests/chain_plugin_tests.cpp
  tests/get_producers_tests.cpp
  tests/get_table_seckey_tests.cpp
  tests/get_table_tests.cpp
  tests/test_chain_plugin.cpp
Labels: enhancement

#931 Remove use of deprecated python distutils
  scripts/postinst
  scripts/prerm
Labels: OCI

#939 Enable tracked_votes processing only if http chain_ro category is configured
  plugins/chain_api_plugin/chain_api_plugin.cpp
  plugins/chain_plugin/chain_plugin.cpp
  plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
  plugins/chain_plugin/include/eosio/chain_plugin/tracked_votes.hpp
  plugins/chain_plugin/tracked_votes.cpp
  plugins/http_plugin/http_plugin.cpp
  plugins/http_plugin/include/eosio/http_plugin/http_plugin.hpp
  tests/chain_plugin_tests.cpp
  tests/get_producers_tests.cpp
  tests/get_table_seckey_tests.cpp
  tests/get_table_tests.cpp
  tests/test_chain_plugin.cpp
Labels: enhancement

#944 Do not store get_info results on accepted_block signal when read_mode is IRREVERSIBLE
  plugins/chain_plugin/get_info_db.cpp
Labels: bug

#950 P2P: Check for is_quitting() for faster shutdown
  plugins/net_plugin/net_plugin.cpp
Labels: OCI

#954 Logging: On startup log number of blocks to be applied from the fork db
  libraries/chain/controller.cpp
Labels: OCI

#937 P2P: Use net threads for connecting and timers
  plugins/net_plugin/net_plugin.cpp
Labels: enhancement, OCI

#949 HTTP: plugin_startup throw on listener error
  plugins/http_plugin/http_plugin.cpp
  plugins/http_plugin/include/eosio/http_plugin/http_plugin.hpp
  plugins/http_plugin/tests/CMakeLists.txt
  plugins/http_plugin/tests/http_plugin_tests.cpp
  unittests/CMakeLists.txt
Labels: OCI

#943 HTTP: Warning and test fix
  plugins/http_plugin/http_plugin.cpp
  plugins/http_plugin/include/eosio/http_plugin/http_plugin.hpp
  plugins/http_plugin/tests/unit_tests.cpp
Labels: OCI

#959 [1.0.3] Test: Update flakey http plugin unit test
  plugins/http_plugin/http_plugin.cpp
  plugins/http_plugin/include/eosio/http_plugin/http_plugin.hpp
  plugins/http_plugin/tests/unit_tests.cpp
Labels: OCI

#960 [1.0.3] Test: Fix flakey production_pause_max_rev_blks_test
  tests/TestHarness/Node.py
  tests/production_pause_max_rev_blks_test.py
Labels: OCI

#966 [1.0.3] Trace_API: Fix get_transaction_trace endpoint fails to return transaction trace if the initial block including the transaction forks out
  plugins/trace_api_plugin/store_provider.cpp
  plugins/trace_api_plugin/test/test_trace_file.cpp
Labels: bug

#969 [1.0.3 -> main] Test: Fix flakey production_pause_max_rev_blks_test
  tests/TestHarness/Node.py
  tests/production_pause_max_rev_blks_test.py
Labels: OCI

#957 [1.0.3] Prometheus: Update speculative block metrics for produced blocks
  plugins/prometheus_plugin/metrics.hpp
Labels: bug, OCI

#975 [1.0.3 -> main] Prometheus: Update speculative block metrics for produced blocks
  plugins/prometheus_plugin/metrics.hpp
Labels: OCI

#976 Handle exceptions in controller signals
  libraries/chain/controller.cpp
  libraries/chain/include/eosio/chain/controller.hpp
  libraries/chain/include/eosio/chain/vote_processor.hpp
  plugins/test_control_api_plugin/test_control_api_plugin.cpp
  plugins/test_control_plugin/include/eosio/test_control_plugin/test_control_plugin.hpp
  plugins/test_control_plugin/test_control_plugin.cpp
  tests/CMakeLists.txt
  tests/TestHarness/Node.py
  tests/nodeos_signal_throw_test.py
  unittests/vote_processor_tests.cpp
Labels: OCI

#979 Test: Refactor: Separate checktime tests
  tests/chain_test_utils.hpp
  tests/test_read_only_trx.cpp
  unittests/CMakeLists.txt
  unittests/api_tests.cpp
  unittests/checktime_tests.cpp
  unittests/test_utils.hpp
Labels: OCI
