Repository AntelopeIO/spring, pull requests merged in 2024-11, with the labels that each got.

#1005 Capture trx_generator output in tests
  tests/TestHarness/TransactionGeneratorsLauncher.py
  tests/trx_generator/trx_generator.cpp
Labels: OCI

#1012 [1.0.4 -> main] Advance fork db root when pending lib greater than head
  libraries/chain/controller.cpp
  unittests/fork_db_tests.cpp
Labels: OCI

#1014 Add details to wasm_execution_error
  libraries/chain/webassembly/runtimes/eos-vm.cpp
Labels: OCI

#965 [1.0.4] skip EOS VM interpreter parallel unit_tests and spec_tests on sanitizer builds
  .github/workflows/build.yaml
Labels: CICD

#1013 eos-vm-oc-whitelist option
  libraries/chain/apply_context.cpp
  libraries/chain/controller.cpp
  libraries/chain/include/eosio/chain/controller.hpp
  libraries/chain/include/eosio/chain/name.hpp
  plugins/chain_plugin/chain_plugin.cpp
  plugins/chain_plugin/test/plugin_config_test.cpp
  unittests/misc_tests.cpp
Labels: enhancement, OCI

#1021 Do not unwind validated blocks on interrupt
  libraries/chain/controller.cpp
  tests/interrupt_trx_test.py
Labels: OCI

#1028 Fix start_block to return correct return code for incomplete apply_block
  libraries/chain/controller.cpp
  plugins/producer_plugin/producer_plugin.cpp
Labels: bug, OCI

#1031 Remove fc dynamic_rethrow_exception
  libraries/chain/include/eosio/chain/exceptions.hpp
  libraries/chain/snapshot_scheduler.cpp
  libraries/libfc/include/fc/exception/exception.hpp
  libraries/libfc/src/exception.cpp
  libraries/testing/tester.cpp
  plugins/http_plugin/include/eosio/http_plugin/macros.hpp
  plugins/producer_api_plugin/producer_api_plugin.cpp
  tests/chain_test_utils.hpp
Labels: OCI

#1034 Do not reject future blocks on speculative nodes
  libraries/chain/include/eosio/chain/controller.hpp
  plugins/net_plugin/net_plugin.cpp
  plugins/producer_plugin/producer_plugin.cpp
Labels: OCI

#1037 [1.0.4 -> main] P2P: Fix peer connections log output
  plugins/net_plugin/net_plugin.cpp
Labels: OCI

#1035 [1.0.4] P2P: Fix sync stuck corner case
  plugins/net_plugin/net_plugin.cpp
Labels: OCI

#1036 Support speculative trx execution in irreversible mode
  libraries/chain/controller.cpp
  libraries/chain/fork_database.cpp
  plugins/chain_plugin/chain_plugin.cpp
  plugins/net_plugin/net_plugin.cpp
  plugins/producer_plugin/producer_plugin.cpp
  tests/CMakeLists.txt
  tests/distributed-transactions-test.py
Labels: documentation, OCI

#1044 [1.0.4] Test fix: Allow for block to not have qc_extension
  tests/separate_prod_fin_test.py
Labels: OCI

#1048 [1.0.4 -> main] Test fix: Allow for block to not have qc_extension
  tests/separate_prod_fin_test.py
Labels: OCI
