Repository AntelopeIO/spring, pull requests merged in 2024-07, with the labels that each got.

#339 Test: Finality Status: Transaction can be forked out multiple times
  tests/trx_finality_status_forked_test.py
Labels: OCI

#335 Update fork choice rules to use timestamp instead of block_num.
  libraries/chain/block_state.cpp
  libraries/chain/finality/finality_core.cpp
  libraries/chain/fork_database.cpp
  libraries/chain/include/eosio/chain/block_state.hpp
  libraries/chain/include/eosio/chain/finality/finality_core.hpp
  libraries/chain/include/eosio/chain/types.hpp
  plugins/net_plugin/net_plugin.cpp
  unittests/deep-mind/deep-mind.log
  unittests/finality_core_tests.cpp
  unittests/finalizer_vote_tests.cpp
  unittests/fork_db_tests.cpp
  unittests/vote_processor_tests.cpp
Labels: consensus-protocol

#347 Refactor fork database
  libraries/chain/controller.cpp
  libraries/chain/fork_database.cpp
  libraries/chain/include/eosio/chain/block_handle.hpp
  libraries/chain/include/eosio/chain/block_state.hpp
  libraries/chain/include/eosio/chain/block_state_legacy.hpp
  libraries/chain/include/eosio/chain/controller.hpp
  libraries/chain/include/eosio/chain/fork_database.hpp
  plugins/chain_plugin/chain_plugin.cpp
  plugins/net_plugin/net_plugin.cpp
  plugins/producer_plugin/producer_plugin.cpp
  tests/nodeos_startup_catchup.py
  unittests/finalizer_vote_tests.cpp
  unittests/fork_db_tests.cpp
  unittests/fork_test_utilities.cpp
  unittests/forked_tests.cpp
Labels: OCI

#350 Move savanna pending lib calculation to forkdb add()
  libraries/chain/block_state.cpp
  libraries/chain/controller.cpp
  libraries/chain/fork_database.cpp
  libraries/chain/include/eosio/chain/block_state.hpp
Labels: OCI

#354 Deep-mind: Log active proposer policy and active finalizer policy with each block
  libraries/chain/controller.cpp
  libraries/chain/deep_mind.cpp
  libraries/chain/include/eosio/chain/deep_mind.hpp
  unittests/deep-mind/deep-mind.log
Labels: OCI

#355 P2P: Reduce log spam of close on shutdown
  plugins/net_plugin/net_plugin.cpp
Labels: OCI

#360 Add performance logs to captured CI/CD log tar
  .github/workflows/build.yaml
Labels: OCI

#364 Rename instant_finality_extension to finality_extension
  libraries/chain/abi_serializer.cpp
  libraries/chain/block_header_state.cpp
  libraries/chain/block_header_state_legacy.cpp
  libraries/chain/block_state.cpp
  libraries/chain/controller.cpp
  libraries/chain/include/eosio/chain/abi_serializer.hpp
  libraries/chain/include/eosio/chain/block_header.hpp
  libraries/chain/include/eosio/chain/block_header_state.hpp
  libraries/chain/include/eosio/chain/block_state.hpp
  libraries/chain/include/eosio/chain/finality/finality_extension.hpp
  libraries/testing/include/eosio/testing/tester.hpp
  plugins/net_plugin/net_plugin.cpp
  unittests/block_header_tests.cpp
  unittests/finality_proof.hpp
  unittests/finality_tests.cpp
  unittests/finalizer_update_tests.cpp
  unittests/producer_schedule_savanna_tests.cpp
  unittests/vote_processor_tests.cpp
Labels: OCI

#373 Write chain_head after vote threads have stopped
  libraries/chain/controller.cpp
Labels: OCI

#365 SHiP: Pull block by block id instead of by block number
  libraries/chain/block_log.cpp
  libraries/chain/controller.cpp
  libraries/chain/fork_database.cpp
  libraries/chain/include/eosio/chain/block_log.hpp
  libraries/chain/include/eosio/chain/controller.hpp
  plugins/chain_interface/include/eosio/chain/plugin_interface.hpp
  plugins/chain_plugin/chain_plugin.cpp
  plugins/net_plugin/net_plugin.cpp
  plugins/state_history_plugin/include/eosio/state_history_plugin/session.hpp
  plugins/state_history_plugin/state_history_plugin.cpp
  tests/block_log.cpp
Labels: OCI

#378 Revert liveness rule only valid for the same finalizer generation changes
  libraries/chain/block_header_state.cpp
  libraries/chain/block_state.cpp
  libraries/chain/controller.cpp
  libraries/chain/finality/finality_core.cpp
  libraries/chain/finality/finalizer.cpp
  libraries/chain/include/eosio/chain/finality/finality_core.hpp
  unittests/deep-mind/deep-mind.log
  unittests/finality_core_tests.cpp
  unittests/finalizer_vote_tests.cpp
  unittests/fork_db_tests.cpp
  unittests/vote_processor_tests.cpp
Labels: consensus-protocol

#359 Fix starting from snapshot created during transition
  libraries/chain/block_header_state_legacy.cpp
  libraries/chain/block_state.cpp
  libraries/chain/block_state_legacy.cpp
  libraries/chain/controller.cpp
  libraries/chain/fork_database.cpp
  libraries/chain/include/eosio/chain/block_header_state_legacy.hpp
  libraries/chain/include/eosio/chain/block_state_legacy.hpp
  libraries/chain/include/eosio/chain/fork_database.hpp
  tests/TestHarness/Node.py
  tests/TestHarness/testUtils.py
  tests/ship_streamer_test.py
  tests/snapshot_in_svnn_transition_test.py
Labels: OCI

#389 Use 2-chain for finality
  libraries/chain/finality/finality_core.cpp
  libraries/testing/include/eosio/testing/tester.hpp
  unittests/block_header_state_tests.cpp
  unittests/block_state_tests.cpp
  unittests/database_tests.cpp
  unittests/deep-mind/deep-mind.log
  unittests/finality_core_tests.cpp
  unittests/finality_proof.hpp
  unittests/finality_test_cluster.hpp
  unittests/finality_tests.cpp
  unittests/finalizer_update_tests.cpp
  unittests/finalizer_vote_tests.cpp
  unittests/forked_tests_savanna.cpp
  unittests/partitioned_block_log_tests.cpp
  unittests/savanna_cluster.hpp
  unittests/svnn_ibc_tests.cpp
Labels: consensus-protocol

#391 Finalizer transition requires QCs on both finalizer policy sets
  libraries/chain/CMakeLists.txt
  libraries/chain/block_header_state.cpp
  libraries/chain/block_state.cpp
  libraries/chain/controller.cpp
  libraries/chain/finality/finalizer.cpp
  libraries/chain/finality/qc.cpp
  libraries/chain/finality/quorum_certificate.cpp
  libraries/chain/include/eosio/chain/block.hpp
  libraries/chain/include/eosio/chain/block_header_state.hpp
  libraries/chain/include/eosio/chain/block_state.hpp
  libraries/chain/include/eosio/chain/controller.hpp
  libraries/chain/include/eosio/chain/finality/finalizer.hpp
  libraries/chain/include/eosio/chain/finality/finalizer_authority.hpp
  libraries/chain/include/eosio/chain/finality/qc.hpp
  libraries/chain/include/eosio/chain/finality/quorum_certificate.hpp
  libraries/chain/include/eosio/chain/snapshot_detail.hpp
  libraries/chain/include/eosio/chain/vote_processor.hpp
  libraries/libfc/include/fc/bitutil.hpp
  libraries/testing/include/eosio/testing/tester.hpp
  plugins/net_plugin/net_plugin.cpp
  plugins/producer_plugin/producer_plugin.cpp
  tests/separate_prod_fin_test.py
  unittests/block_state_tests.cpp
  unittests/deep-mind/deep-mind.log
  unittests/finality_misc_tests.cpp
  unittests/finality_proof.hpp
  unittests/finality_test_cluster.hpp
  unittests/finality_tests.cpp
  unittests/savanna_cluster.cpp
  unittests/savanna_cluster.hpp
  unittests/svnn_ibc_tests.cpp
  unittests/test-contracts/savanna/common/savanna.hpp
  unittests/test-contracts/savanna/ibc/ibc.abi
  unittests/test-contracts/savanna/ibc/ibc.wasm
  unittests/vote_processor_tests.cpp
Labels: consensus-protocol, OCI

#392 Add `timestamp` and `parent_timestamp` to finality leaf nodes.
  libraries/chain/block_state.cpp
  libraries/chain/include/eosio/chain/block_state.hpp
  unittests/deep-mind/deep-mind.log
  unittests/test-contracts/savanna/common/savanna.hpp
  unittests/test-contracts/savanna/ibc/ibc.abi
Labels: consensus-protocol

#397 Replace final_on_strong_qc_block_num in finality digest with other needed data
  libraries/chain/block_header_state.cpp
  libraries/chain/block_state.cpp
  libraries/chain/include/eosio/chain/block_header_state.hpp
  libraries/chain/include/eosio/chain/block_state.hpp
  libraries/state_history/abi.cpp
  unittests/deep-mind/deep-mind.log
  unittests/finality_proof.hpp
Labels: consensus-protocol

#402 Add producer, timestamp, and latency to missing vote log output
  plugins/producer_plugin/producer_plugin.cpp
Labels: OCI

#408 Move LIB in commit block under normal conditions
  libraries/chain/controller.cpp
  unittests/deep-mind/deep-mind.log
Labels: OCI

#420 Only vote on recent blocks
  libraries/chain/controller.cpp
  libraries/chain/finality/finalizer.cpp
  libraries/chain/include/eosio/chain/controller.hpp
  libraries/chain/include/eosio/chain/finality/finalizer.hpp
  libraries/testing/include/eosio/testing/tester.hpp
  libraries/testing/tester.cpp
  unittests/savanna_cluster.hpp
  unittests/state_history_tests.cpp
Labels: OCI

#426 [1.0-beta4] Test: Provide more time for connections to be established
  tests/disaster_recovery_2.py
Labels: OCI

#428 [1.0-beta4 -> main] Test: Provide more time for connections to be established
  tests/disaster_recovery_2.py
Labels: OCI

#429 [1.0-beta4] Test: Increase leeway for trx_finality_status_test
  tests/trx_finality_status_test.py
Labels: OCI

#430 [1.0-beta4] Test: Reduce connection retry interval
  tests/TestHarness/Cluster.py
Labels: OCI

#431 [1.0-beta4 -> main] Test: Increase leeway for trx_finality_status_test
  tests/trx_finality_status_test.py
Labels: OCI

#432 [1.0-beta4 -> main] Test: Reduce connection retry interval
  tests/TestHarness/Cluster.py
Labels: OCI

#433 [1.0-beta4] Test: forkdb can be ahead of chain head in speculative/head mode
  tests/nodeos_irreversible_mode_test.py
Labels: OCI

#435 [1.0-beta4 -> main] Test: forkdb can be ahead of chain head in speculative/head mode
  tests/nodeos_irreversible_mode_test.py
Labels: OCI

#434 [1.0-beta4] Log when block has no QCs
  libraries/chain/controller.cpp
  libraries/chain/fork_database.cpp
  plugins/producer_plugin/producer_plugin.cpp
Labels: OCI

#449 [1.0-beta4 -> main] Log when block has no QCs
  libraries/chain/controller.cpp
  libraries/chain/fork_database.cpp
  plugins/producer_plugin/producer_plugin.cpp
Labels: OCI

#451 [1.0-beta4] Some misc improvements
  libraries/chain/controller.cpp
  libraries/chain/finality/finalizer.cpp
  libraries/chain/fork_database.cpp
  libraries/chain/include/eosio/chain/controller.hpp
  libraries/chain/include/eosio/chain/finality/finalizer.hpp
  libraries/testing/tester.cpp
  plugins/producer_plugin/producer_plugin.cpp
  unittests/finalizer_tests.cpp
Labels: OCI

#452 [1.0-beta4 -> main] Some misc improvements
  libraries/chain/controller.cpp
  libraries/chain/finality/finalizer.cpp
  libraries/chain/fork_database.cpp
  libraries/chain/include/eosio/chain/controller.hpp
  libraries/chain/include/eosio/chain/finality/finalizer.hpp
  libraries/testing/tester.cpp
  plugins/producer_plugin/producer_plugin.cpp
  unittests/finalizer_tests.cpp
Labels: OCI
